### ISSUE TITLE
Error when trying to connect

### ISSUE THREAD

**Issue by ghost** [gridsum/NHBaseAPI#3]
I've used another Thrift API to connect to hbase previously, but now I'm trying NHBaseAPI. When I try to connect using:

string connectionStr = "zk=[my port]:2181";
IHBaseClient client = new HBaseClient(connectionStr);

I get the following error:

The following InnerException reported: System.TypeInitializationException: The type initializer for 'Gridsum.NHBaseThrift.Client.HBaseClient' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Gridsum.NHBaseThrift.Contracts.ThriftObject' threw an exception. ---> System.TypeInitializationException: The type initializer for 'KJFramework.Tracing.TracingManager' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at KJFramework.Tracing.TracingManager.LoadProvider()
   at KJFramework.Tracing.TracingManager..cctor()
   --- End of inner exception stack trace ---
   at KJFramework.Tracing.TracingManager.TraceItemWatcher()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   --- End of inner exception stack trace ---
   at Gridsum.NHBaseThrift.Contracts.ThriftObject..ctor()
   at Gridsum.NHBaseThrift.Messages.ThriftMessage..ctor()
   at Gridsum.NHBaseThrift.Messages.AtomicIncrementRequestMessage..ctor() in e:\NHaseAPI\NHBaseThrift\Messages\AtomicIncrementRequestMessage.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Gridsum.NHBaseThrift.Network.ThriftProtocolStack.AutoInitialize() in e:\NHaseAPI\NHBaseThrift\Network\ThriftProtocolStack.cs:line 124
   at Gridsum.NHBaseThrift.Network.ThriftProtocolStack..ctor() in e:\NHaseAPI\NHBaseThrift\Network\ThriftProtocolStack.cs:line 21
   at Gridsum.NHBaseThrift.Client.HBaseClient..cctor() in e:\NHaseAPI\NHBaseThrift\Client\HBaseClient.cs:line 74
   --- End of inner exception stack trace ---
   at Gridsum.NHBaseThrift.Client.HBaseClient..ctor(String connectionStr)

Any suggestions of what may be wrong? I ca confirm my hbase instance is up because I can use HareDBClient to access the data in my hbase table.

Thanks.

**Comment by DexterL** [comment]
"xxxxxx" represented the IP address.It used three times, because of zookeeper cluster had three nodes in general case.
So

``` c#
string connectionStr = "zk=xxxxxx:2181,xxxxxx:2181,xxxxxx:2181";
```

should be：

``` c#
string connectionStr = "zk=192.168.1.100:2181,192.168.1.101:2181,192.168.1.102:2181";
```

I'll change the Readme file soon
